apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: combined
  namespace: kafka
  labels:
    strimzi.io/cluster: demo
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: ephemeral
  jvmOptions:
    -Xms: 256m
    -Xmx: 512m
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 1000m
